
   - name: Install Prerequisites for GIP
     apt:
       name:
         - gnupg2
         - curl
         - software-properties-common

   - name: Adding Grafana Repository Key
     apt_key:
       url: https://packages.grafana.com/gpg.key

   - name: Adding the APT Repository of Grafana
     apt_repository:
       repo: "deb https://packages.grafana.com/oss/deb stable main"
       state: present

   - name: Adding InfluxDB Repository Key
     apt_key:
       url: https://repos.influxdata.com/influxdata-archive_compat.key

   - name: Adding the APT Repository of InfluxDB
     apt_repository:
       repo: 'deb [signed-by=/etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg] https://repos.influxdata.com/debian stable main'
       state: present

   - name: Reloading Packages via Update
     apt:
       upgrade: dist
       update_cache: yes

   - name: Install Grafana, InfluxDB, and Prometheus in Ubuntu
     apt:
       name:
         - prometheus
         - grafana
         - influxdb2

   - name: Enable and Start Grafana, InfluxDB and Prometheus in Ubuntu
     systemd:
       name: "{{ item }}"
       state: restarted
       enabled: true
     loop:
       - prometheus
       - grafana-server
       - influxdb

   - name: Enable TCP ports for InfluxDB and Prometheus
     shell: |
       sudo ufw allow 9090/tcp
       sudo ufw allow 8086/tcp
















































